services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
    logging:
      driver: fluentd
      options:
        tag: "app-firelens-deadbeef"
        fluentd-async-connect: "true"
    depends_on:
      - fluent-bit
  fluent-bit:
    image: fluent/fluent-bit:latest
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "24224:24224"
    environment:
      REQTIME_THRESHOLD: 0.5
      STATUS_THRESHOLD: 501
